---
- name: "{{ apicall }}"
  uri:
    url: "{{ passwordstate_host }}api/folders/"
    validate_certs: "{{ validate_certs }}"
    headers:
      APIKey: "{{ systemwide_apikey }}"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: GetFolders