---
- name: "{{ apicall }} facts"
  vars:
    querystring: ""

  set_fact:
    querystring: 
      "{{querystring}}{{ item.param }}={{ item.criteria |
         replace(' ','%20') }}&"
  loop: "{{ params }}"

- name: "{{ apicall }}"
  uri:
    url: "{{ ''.join((passwordstate_host,
      'api/folders/?',
      querystring |trim('&') ))}}"
    validate_certs: "{{ validate_certs }}"
    headers:
      APIKey: "{{ systemwide_apikey }}"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: GetFolder