---
- block:
  - name: "Load Post Data: {{ passwordstate_apicall }}"
    include_role:
      name: ansible-role-passwordstate
      tasks_from: createpostpayload
    when: passwordstate_postdata is defined

  - name: "Load Query String for {{ passwordstate_apicall }}"
    include_role:
      name: ansible-role-passwordstate
      tasks_from: createquerystring
    when: passwordstate_params is defined

  - name : Set the api_method so we can set the status code
    set_fact:
      api_method: "{{ passwordstate_api_method | default('GET') | upper }}"

  # Fire the api call 
  - name: "{{ passwordstate_apicall }}"
    uri:
      url: "{{ passwordstate_baseurl if api_method != 'GET' else
        '/'.join (( passwordstate_baseurl, passwordstate_params[0].value )) }}"
      validate_certs: "{{ validate_certs }}"
      headers:
        APIKey: "{{ passwords_apikey }}"
      method: "{{ api_method }}"
      return_content: yes
      status_code: "{{ '201' if api_method | upper == 'POST' else
        '200' if api_method | upper == 'PUT' else '200'}}"
      body: "{{ passwordstate_postpayload | default(omit) }}"
      body_format: json
    register: password
