---
- name: "Load Query String for {{ passwordstate_apicall }}"
  include_role:
    name: ansible-role-passwordstate
    tasks_from: createquerystring

  # Fire the api call, trimming the ending &
- name: "{{ passwordstate_apicall }}"
  uri:
    url: "{{ passwordstate_url }}"
    validate_certs: "{{ validate_certs }}"
    headers:
      # Allow fail back to system wide api key for all passwords search
      APIKey: "{{ passwords_apikey | default(systemwide_apikey) }}"
    method: GET
    return_content: yes
    status_code:
      - 200
      - 404 # permissable on search
    body_format: json
  register: searchpasswords